---
- name: '[OCP4-AUTO-INSTALL] Configure an Openshift4 cluster'
  hosts: localhost
  connection: local
  vars_files:
    - vars/vars.yml
  tasks:
    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][INFRA-NODES] Deploy and configure Infra Nodes'
      include_role:
        name: "ocp4-post-infra-nodes"
      when:
        - infra_nodes is defined
        - infra_nodes | bool
