---
- name: '[OCP4-AUTO-INSTALL] Configure an Openshift4 cluster'
  hosts: localhost
  connection: local
  vars_files:
    - vars/vars.yml
  tasks:
    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][CERT-MANAGER] Configure Cert Manager'
      include_role:
        name: "ocp4-post-cert-manager"
      when:
        - cmanager is defined
        - cmanager | bool
