---
- name: '[OCP4-AUTO-INSTALL] Deploy an Openshift4 cluster'
  hosts: localhost
  connection: local
  vars_files:
    - vars/vars.yml
    - vault/vault.yml
  tasks:

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][WORKER-NODES] Configure Worker Nodes'
      include_role:
        name: "ocp4-post-worker-nodes"
      when:
        - worker_nodes is defined
        - worker_nodes | bool

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][INFRA-NODES] Deploy and configure Infra Nodes'
      include_role:
        name: "ocp4-post-infra-nodes"
      when:
        - infra_nodes is defined
        - infra_nodes | bool

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][OAUTH] Configure OAuth'
      include_role:
        name: "ocp4-post-oauth"
      when:
        - oauth is defined
        - oauth != False

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][LOGGING] Install and configure Logging'
      include_role:
        name: "ocp4-post-logging"
      when:
        - logging is defined
        - logging | bool

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][MONITORING] Configure Monitoring'
      include_role:
        name: "ocp4-post-monitoring"
      when:
        - monitoring is defined
        - monitoring | bool

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][REGISTRY] Install and configure Registry'
      include_role:
        name: "ocp4-post-registry"
      when:
        - registry is defined
        - registry | bool

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL][SERVICE-MESH] Install and configure Service Mesh'
      include_role:
        name: "ocp4-post-service-mesh"
      when:
        - service_mesh is defined
        - service_mesh | bool

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL] Install and configure Argocd'
      include_role:
        name: "ocp4-post-argocd"
      when:
        - argocd is defined
        - argocd | bool

    - name: '[OCP4-AUTO-INSTALL][POST-INSTALL] Disable Operator Hub'
      include_role:
        name: "ocp4-post-operatorhub"
      when:
        - disable_operator_hub is defined
        - disable_operator_hub | bool
...
