---
- name: '{{ cmanager_label }} Installing Certificates on route'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template','./templates/certificates.yml.j2' ) | from_yaml }}"
  loop: '{{ cmanager_cert_routes }}' 

- name: '{{ cmanager_label }} Patch default certificate'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    kind: ingresscontroller
    api_version: operator.openshift.io/v1
    name: default
    namespace: openshift-ingress-operator
    kubeconfig: "{{ kubeconfig }}"
    definition: "{{ lookup('template', './files/cert-patch-ingress-operator.yml' ) | from_yaml }}"



