---

- name: '[OCP4-POSTINSTALL][MACHINESET] Fetch cluster information about the Infrastructure'
  k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    api_version: config.openshift.io/v1
    kind: Infrastructure
    name: cluster
  register: cluster_info

- name: '[POSTINSTALL][MACHINESET] Show info about the cluster of OCP4'
  debug:
    msg: "{{ cluster_info }}"

- name: '[POSTINSTALL][MACHINESET] Build the {{ node_labels }} machineset facts'
  set_fact:
    machineset:
      infra_node_replicas: "{{ infra_node_replicas }}"
      infrastructure_id: "{{ cluster_info.resources.0.status.infrastructureName }}"
      node_labels: "{{ node_labels }}"
      disk_size: "{{ infra_disk_size }}"
      memory_size: "{{ infra_memory_size }}"
      taints: "{{ taints if taints is defined else omit }}"
      name_identifier: "{{ name_identifier }}"

- name: '[POSTINSTALL][MACHINESET] Display the data for the {{ node_labels }} machinesets'
  debug:
    var: machineset

- name: '[POSTINSTALL][MACHINESET] Create the {{ node_labels }} machineset'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: openshift-machine-api
    api_version: machine.openshift.io/v1beta1
    kind: MachineSet
    state: present
    resource_definition: "{{ lookup('template', 'templates/machineset.j2') }}"
    validate_certs: false
...
