apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  annotations:
{%if clo_node_selector is defined %}
    openshift.io/node-selector: "{{ clo_node_selector }}"
{% endif %}
  labels:
    openshift.io/cluster-logging: "true"
    openshift.io/cluster-monitoring: "true"
