---

- name: '[POSTINSTALL][WORKER-NODES] Interrogate cluster'
  k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    api_version: config.openshift.io/v1
    kind: Infrastructure
    name: cluster
  vars:
    ansible_python_interpreter: "{{ user_path }}/virtualEnvironment2.7/bin/python"
  environment:
    PYTHONPATH: "/var/lib/awx/venv/ansible/lib/python2.7/site-packages:/var/lib/awx/venv/awx/lib64/python3.6/site-packages/ansible_runner/callbacks:{{ user_path }}/virtualEnvironment2.7/lib/python2.7/site-packages/"
  register: infradata

- name: '[POSTINSTALL][WORKER-NODES] Capture nodes'
  k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    kind: Node
  vars:
    ansible_python_interpreter: "{{ user_path }}/virtualEnvironment2.7/bin/python"
  environment:
    PYTHONPATH: "/var/lib/awx/venv/ansible/lib/python2.7/site-packages:/var/lib/awx/venv/awx/lib64/python3.6/site-packages/ansible_runner/callbacks:{{ user_path }}/virtualEnvironment2.7/lib/python2.7/site-packages/"
  register: nodedata
