---
# tasks file for tower_ldap_settings
- include_vars:
    file: "{{ item }}"
  loop:
    - "vars/configure_tower_general.yml"
    - "vars/configure_tower_vault.yml"
    - "vars/configure_tower_credentials.yml"
  when:
    - configure_tower_credentials is not defined

- name: "Configure Tower Credentials | Launch credential creation"
  ansible.tower.tower_credential:
    tower_username: "{{ configure_tower_username }}"
    tower_password: "{{ configure_tower_password }}"
    tower_host: "{{ configure_tower_server }}"
    validate_certs: "{{ configure_tower_validate_certs }}"
    name: "{{ item.name }}"
    organization: "{{ item.organization | default('Default') }}"
    description: "{{ item.description | default (omit) }}"
    credential_type: "{{ item.credential_type }}"
    host: "{{ item.host | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    team: "{{ item.team | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    inputs: "{{ item.inputs | default(omit) }}"
  loop: "{{ configure_tower_credentials }}"
  when: configure_tower_credentials is defined
  delegate_to: "{{ 'localhost' if tower_local else omit }}"
  no_log: true
  async: 1000
  poll: 0
  register: credentials1

- name: "Configure Tower Credentials | Wait for finish the credential creation"
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: credentials1_result
  until: credentials1_result.finished
  retries: 10
  loop: "{{ credentials1.results }}"
  delegate_to: "{{ 'localhost' if tower_local else omit }}"
  no_log: true
...
