---
# tasks file for configure_tower_credential_types
- include_vars:
    file: "{{ item }}"
  loop:
    - "configure_tower_general.yml"
    - "configure_tower_vault.yml"
    - "configure_tower_credential_types.yml"
  when:
    - configure_tower_credential_types is not defined

- name: "Configure Tower Credential Types | Launch credential types creation"
  ansible.tower.tower_credential_type:
    tower_username: "{{ configure_tower_username }}"
    tower_password: "{{ configure_tower_password }}"
    tower_host: "{{ configure_tower_server }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default (omit) }}"
    kind: "{{ item.kind }}"
    inputs: "{{ item.inputs | default(omit) }}"
    injectors: "{{ item.injectors | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    validate_certs: "{{ configure_tower_validate_certs }}"
  loop: "{{ configure_tower_credential_types }}"
  when: configure_tower_credential_types is defined
  delegate_to: "{{ 'localhost' if tower_local else omit }}"
  # no_log: true
  async: 1000
  poll: 0
  register: credentialTypes1

- name: "Configure Tower Credential Types | Wait for finish the credential types creation"
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: credentialTypes1_result
  until: credentialTypes1_result.finished
  retries: 10
  loop: "{{ credentialTypes1.results }}"
  delegate_to: "{{ 'localhost' if tower_local else omit }}"
...
