---
- name: '[OCP4-INSTALL][DOWNLOAD] Create a user-writable directory for tools'
  file:
    name: "{{ user_path }}"
    state: directory

- name: '[OCP4-INSTALL][DOWNLOAD] Download the required ocp4 tooling'
  get_url:
    url: "{{ var_installer_baseurl }}/{{ pkg }}"
    dest: "{{ user_path }}/{{ pkg }}"
  loop:
    - "{{ var_installer_program }}"
    - "{{ var_installer_clienttools }}"
    - "{{ var_virtual_environment }}"
  loop_control:
    loop_var: pkg
  register: ocp4_files
  retries: 3
  delay: 3
  until: ocp4_files is not failed

- name: '[OCP4-INSTALL][DOWNLOAD] Ensure downloaded installers are unarchived'
  unarchive:
    src: "{{ user_path }}/{{ pkg }}"
    dest: "{{ user_path }}"
  loop:
    - "{{ var_installer_program }}"
    - "{{ var_installer_clienttools }}"
  loop_control:
    loop_var: pkg
  when: ocp4_files.changed
...
