---
- name: '[OCP4 INSTALL][PRINT-INFO] Pause for 5 minutes'
  pause:
    minutes: 5
  when: not tower_used

- name: '[OCP4 INSTALL][PRINT-INFO] Get ClusterVersion'
  k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    api_version: config.openshift.io/v1
    kind: dns
    name: cluster
  register: r_cluster_version
  vars:
    ansible_python_interpreter: "{{ user_path }}/virtualEnvironment2.7/bin/python"
  environment:
    PYTHONPATH: "/var/lib/awx/venv/ansible/lib/python2.7/site-packages:/var/lib/awx/venv/awx/lib64/python3.6/site-packages/ansible_runner/callbacks:{{ user_path }}/virtualEnvironment2.7/lib/python3.6/site-packages/"

- name: '[OCP4 INSTALL][PRINT-INFO] Extract the baseDomain'
  set_fact:
    ocp4_domain: "apps.{{ r_cluster_version.resources.0.spec.baseDomain }}"

- name: '[OCP4 INSTALL][PRINT-INFO] Gather OCP4 Console & API'
  set_fact:
    ocp4_console: "https://console-openshift-console.{{ ocp4_domain }}"
    ocp4_api: "https://api.{{ ocp4_domain }}"

- name: '[OCP4 INSTALL][PRINT-INFO] Gather Connection Information'
  set_fact:
    info: "{{ (info | default([])) + [item.split('\n')] | flatten }}"
  vars:
    - command: |
        regex='Login to the console with user:\s*\\"([^\\"]*)\\"[^\\"]*\\"([^\\"]*)\\"' && [[ $(</var/lib/awx/tmp/ephemeral/.openshift_install.log) =~ $regex ]] && echo "Username: ${BASH_REMATCH[1]} ; Password: ${BASH_REMATCH[2]}"
  with_items:
    - "Openshift Master Console: {{ ocp4_console | trim }}"
    - "Openshift API for command line 'oc' client: {{ ocp4_api | trim }}"
    - "Openshift Initial credentials: {{ lookup('pipe', command) }}"
    - |
        Openshift nodes private key (for core user connection):
        {{ idrsa.content | b64decode }}
    - |
        Openshift kubeconfig:
        {{ res_kubeconfig.content | b64decode }}

- name: '[OCP4 INSTALL][PRINT-INFO] Print Connection Information'
  debug:
    var: info
...
