---
# tasks file for ocp4-post-project-template-request

- name: '[POSTINSTALL][PROJECT-REQUEST-TEMPLATE] Create and enable Project Request Template'
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - ./templates/project_request_template.j2
  - ./templates/project_request_config.j2

- name: '[POSTINSTALL][PROJECT-REQUEST-TEMPLATE] Add label to openshift-ingress project'
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
  - ./files/openshift-ingress-namespaces.yaml
  when: install_network_policies | bool
